### ISSUE TITLE
Design Docs Checklist

### ISSUE THREAD

**Issue by mkayys** [kaycbas/rocket#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

## Comments

---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://open.appacademy.io/learn/swe-in-person/full-stack-project/mvp-checklist) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

## Comments
- You might want to flip the order of your MVP 3 and 4 because you want articles first to test "managing" them `done` 
    * `Response:` That makes sense, I flipped them. I originally gave them that order because 'Manage' will be the homepage view. I'm assume there won't be any issues with implementing a non-homepage first?

---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments
- missing `backticks` on column names, (i.e. `id`, `username`) <-- still missing this styling (`done` misinterpreted the first time)
- what is the purpose of the `discover` column in the `articles` table? to indicate whether this article is "featured" on the discover page?
    * `Response:` Yes, it's which articles are featured on the Discover page. I like 'featured' better though, I just switched it.
- will not need `img_url` column for `articles` table (`done`)
- also table names need to be lowercased (`done`)

---

# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments
- In the `saves` slice of state, the `archived` and `favorited` is both true, is that possible? That an article can be in multiple categories(i.e. my list, archives, favorites)?
    * `Response:` Articles can be in either List or Archive, but not both. However, articles can be added to Favorites regardless if they're in List or Archive. So you could have an Archived article that's also in Favorites.

- just to be semantic, may want to consider having the `session` slice of state key of `user` be `currentUser` (just a suggestion) (`agreed`)

---

# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments
* I've got some questions about my routes, specifically how I should be managing the 'Saves', which is a joins table between Article and User that also has some information about the type of save (i.e. archive, favorite). I'll try to reach out tomorrow (thurs).

- for the `DELETE /api/articles/:article_id/favorites`, description says "un-favorites and article" instead of "un-favorites AN article"; also to move the favorites entry, you may need the id of the specific favorite to remove that row from the database
    * fixed the typo and edited favorite's DELETE route to be /favorites/:id, then put the favoriteId in the article's state slice
---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

## Comments
